# STUDENT PORTFOLIO
print("portfolio of student")
name = input("Enter your name:-")
class1 = input("Enter your class:-")
division = input("Enter your section:-")
rollno = int(input("Enter your roll no.:-"))
print("enter the name of the subjects")
subject1_eng =int(input("Enter the marks of english:-"))
subject2_maths = int(input("Enter the marks of maths:-"))
subject3_science = int(input("Enter the marks of science:-"))

print("Details of the student")
print("enter your name:-",name)
print("enter your class & section:-",class1,"-",division)
print("enter your roll no.:-",rollno)
print("marks of english :-",subject1_eng)
print("marks of maths :-",subject2_maths)
print("marks of science :-",subject3_science)
print("percentage of",name, ":" , ((subject1_eng+subject2_maths+subject3_science)*100)/300)
